package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-10-10T10:05:00.235+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ ObjectFactory.class })
public interface Service1Soap {

    @WebResult(name = "GetAccountsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccounts",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetAccounts")
    @WebMethod(operationName = "GetAccounts", action = "http://tempuri.org/GetAccounts")
    @ResponseWrapper(localName = "GetAccountsResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetAccountsResponse")
    Result getAccounts();

    @WebResult(name = "GetEmployeesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployees",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetEmployees")
    @WebMethod(operationName = "GetEmployees", action = "http://tempuri.org/GetEmployees")
    @ResponseWrapper(localName = "GetEmployeesResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetEmployeesResponse")
    Result getEmployees();

    @WebResult(name = "WbsUserObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WbsUserObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsUserObject")
    @WebMethod(operationName = "WbsUserObject", action = "http://tempuri.org/WbsUserObject")
    @ResponseWrapper(localName = "WbsUserObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsUserObjectResponse")
    org.tempuri.WbsUser wbsUserObject();

    @WebResult(name = "GetContractOfItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetContractOfItem",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetContractOfItem")
    @WebMethod(operationName = "GetContractOfItem", action = "http://tempuri.org/GetContractOfItem")
    @ResponseWrapper(localName = "GetContractOfItemResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetContractOfItemResponse")
    Result getContractOfItem(@WebParam(name = "itemId", targetNamespace = "http://tempuri.org/") String itemId);

    @WebResult(name = "WbsPrjPhaseObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WbsPrjPhaseObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsPrjPhaseObject")
    @WebMethod(operationName = "WbsPrjPhaseObject", action = "http://tempuri.org/WbsPrjPhaseObject")
    @ResponseWrapper(localName = "WbsPrjPhaseObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsPrjPhaseObjectResponse")
    org.tempuri.WbsPrjPhase wbsPrjPhaseObject();

    @WebResult(name = "UserObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.UserObject")
    @WebMethod(operationName = "UserObject", action = "http://tempuri.org/UserObject")
    @ResponseWrapper(localName = "UserObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.UserObjectResponse")
    org.tempuri.User userObject();

    @WebResult(name = "GetItemWbsInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemWbsInfo",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetItemWbsInfo")
    @WebMethod(operationName = "GetItemWbsInfo", action = "http://tempuri.org/GetItemWbsInfo")
    @ResponseWrapper(localName = "GetItemWbsInfoResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetItemWbsInfoResponse")
    Result getItemWbsInfo(@WebParam(name = "itemId", targetNamespace = "http://tempuri.org/") java.lang.String itemId);

    @WebResult(name = "ItemObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ItemObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.ItemObject")
    @WebMethod(operationName = "ItemObject", action = "http://tempuri.org/ItemObject")
    @ResponseWrapper(localName = "ItemObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.ItemObjectResponse")
    org.tempuri.Item itemObject();

    @WebResult(name = "GetEpibolyContractOfItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEpibolyContractOfItem",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetEpibolyContractOfItem")
    @WebMethod(operationName = "GetEpibolyContractOfItem", action = "http://tempuri.org/GetEpibolyContractOfItem")
    @ResponseWrapper(localName = "GetEpibolyContractOfItemResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetEpibolyContractOfItemResponse")
    Result getEpibolyContractOfItem(@WebParam(name = "itemId", targetNamespace = "http://tempuri.org/") String itemId);

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.HelloWorldResponse")
    java.lang.String helloWorld();

    @WebResult(name = "GetDeptsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDepts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDepts")
    @WebMethod(operationName = "GetDepts", action = "http://tempuri.org/GetDepts")
    @ResponseWrapper(localName = "GetDeptsResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetDeptsResponse")
    Result getDepts();

    @WebResult(name = "GetItemsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItems", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItems")
    @WebMethod(operationName = "GetItems", action = "http://tempuri.org/GetItems")
    @ResponseWrapper(localName = "GetItemsResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetItemsResponse")
    Result getItems();

    @WebResult(name = "GetCostOfItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCostOfItem",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetCostOfItem")
    @WebMethod(operationName = "GetCostOfItem", action = "http://tempuri.org/GetCostOfItem")
    @ResponseWrapper(localName = "GetCostOfItemResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.GetCostOfItemResponse")
    Result getCostOfItem(@WebParam(name = "itemId", targetNamespace = "http://tempuri.org/") java.lang.String itemId);

    @WebResult(name = "ItemWbsObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ItemWbsObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.ItemWbsObject")
    @WebMethod(operationName = "ItemWbsObject", action = "http://tempuri.org/ItemWbsObject")
    @ResponseWrapper(localName = "ItemWbsObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.ItemWbsObjectResponse")
    org.tempuri.ItemWbs itemWbsObject();

    @WebResult(name = "SendMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendMessage",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.SendMessage")
    @WebMethod(operationName = "SendMessage", action = "http://tempuri.org/SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.SendMessageResponse")
    Result sendMessage(@WebParam(name = "msg", targetNamespace = "http://tempuri.org/") java.lang.String msg,
                       @WebParam(name = "receiverIds", targetNamespace = "http://tempuri.org/") String receiverIds,
                       @WebParam(name = "receiverNames", targetNamespace = "http://tempuri.org/") String receiverNames);

    @WebResult(name = "WbsMajorObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WbsMajorObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsMajorObject")
    @WebMethod(operationName = "WbsMajorObject", action = "http://tempuri.org/WbsMajorObject")
    @ResponseWrapper(localName = "WbsMajorObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsMajorObjectResponse")
    org.tempuri.WbsMajor wbsMajorObject();

    @WebResult(name = "UserLoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserLogin",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.UserLogin")
    @WebMethod(operationName = "UserLogin", action = "http://tempuri.org/UserLogin")
    @ResponseWrapper(localName = "UserLoginResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.UserLoginResponse")
    Result userLogin(@WebParam(name = "loginName", targetNamespace = "http://tempuri.org/") java.lang.String loginName,
                     @WebParam(name = "loginPwd", targetNamespace = "http://tempuri.org/") java.lang.String loginPwd);

    @WebResult(name = "AccountObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AccountObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.AccountObject")
    @WebMethod(operationName = "AccountObject", action = "http://tempuri.org/AccountObject")
    @ResponseWrapper(localName = "AccountObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.AccountObjectResponse")
    org.tempuri.Account accountObject();

    @WebResult(name = "ContractObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ContractObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.ContractObject")
    @WebMethod(operationName = "ContractObject", action = "http://tempuri.org/ContractObject")
    @ResponseWrapper(localName = "ContractObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.ContractObjectResponse")
    org.tempuri.Contract contractObject();

    @WebResult(name = "DeptObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeptObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.DeptObject")
    @WebMethod(operationName = "DeptObject", action = "http://tempuri.org/DeptObject")
    @ResponseWrapper(localName = "DeptObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.DeptObjectResponse")
    org.tempuri.Dept deptObject();

    @WebResult(name = "WbsSubEntryObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WbsSubEntryObject",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsSubEntryObject")
    @WebMethod(operationName = "WbsSubEntryObject", action = "http://tempuri.org/WbsSubEntryObject")
    @ResponseWrapper(localName = "WbsSubEntryObjectResponse",
            targetNamespace = "http://tempuri.org/",
            className = "org.tempuri.WbsSubEntryObjectResponse")
    org.tempuri.WbsSubEntry wbsSubEntryObject();
}
